version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-browsers
    working_directory: /tmp/rnb-components
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm prune && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm run test -- --maxWorkers 2
      - store_artifacts:
          path: coverage/lcov-report/
      - run:
          name: Build
          command: npm run build
      - deploy:
          name: Publish
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            npm publish --access public
