version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.14.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Login to NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Install dependencies
          command: npm prune && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm run test -- --maxWorkers 2
      - store_artifacts:
          path: coverage/lcov-report/
      - run:
          name: Build
          command: npm run build
      - run:
          name: Publish
          command: npm publish --access public

workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          context: redandblue
          filters:
            branches:
              only: master
